// frontend/src/app/carbon-footprint/page.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { clearTokens } from "@/src/lib/api/auth";
import { getCurrentUser } from "@/src/lib/api";
import { getCarbonFootprintStats, listCarbonFootprints } from "@/src/lib/api/carbon_footprint";
import type { User } from "@/src/types/user";
import type { CarbonFootprintStats, CarbonFootprintResponse } from "@/src/types/carbon_footprint";
import StatCard from "@/src/components/ui/StatCard";
import { CategoryBars, WeeklyTrend } from "@/src/components/dashboard/charts";
import WeeklyScore from "@/src/components/ui/WeeklyScore";
import Link from "next/link";

export default function CarbonFootprintPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null);
  const [stats, setStats] = useState<CarbonFootprintStats | null>(null);
  const [recent, setRecent] = useState<CarbonFootprintResponse[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>("");

  const loadData = useCallback(async () => {
    try {
      setError("");
      const [u, s, r] = await Promise.all([
        getCurrentUser(),
        getCarbonFootprintStats(),
        listCarbonFootprints({ limit: 10 }),
      ]);
      setUser(u);
      setStats(s);
      setRecent(r);
    } catch {
      clearTokens();
      setError("Session expired. Please sign in again.");
      router.replace("/login");
    } finally {
      setLoading(false);
    }
  }, [router]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  if (loading) return <p className="p-4 text-white">Loading…</p>;
  if (error) return <p className="p-4 text-red-400">{error}</p>;

  const totalEmitted = stats?.total_co2_emitted ?? 0;
  const totalEntries = stats?.total_entries ?? 0;

  return (
    <div className="mx-auto max-w-6xl space-y-6 p-4 md:p-6">
      {/* Header */}
      <header className="rounded-[32px] border border-white/10 bg-[radial-gradient(circle_at_top_left,_rgba(111,207,69,0.2),_transparent_55%)] p-6 shadow-[0_25px_70px_rgba(0,0,0,0.3)]">
        <h1 className="text-3xl font-semibold text-white">Carbon Footprint</h1>
        <p className="mt-2 text-sm text-white/70">Track the emissions generated by your lifestyle.</p>
      </header>

      {/* Weekly score (using carbon stats for emitted only) */}
      <WeeklyScore greenStats={null} carbonStats={stats} />

      {/* Stat cards */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <StatCard label="CO₂ Emitted" value={totalEmitted.toFixed(2)} unit="kg" accent="#f07030" sub={`${totalEntries} entries`} />
        <StatCard label="Total Entries" value={String(totalEntries)} accent="#f07030" />
      </div>

      {/* Weekly trend – only emitted data */}
      <div className="rounded-[28px] border border-white/10 bg-[#07140d] p-5 shadow-[0_22px_70px_rgba(0,0,0,0.35)]">
        <h2 className="mb-3 text-lg font-semibold text-white">Weekly Trend</h2>
        <WeeklyTrend saved={[]} emitted={stats?.weekly_trend ?? []} />
      </div>

      {/* Category breakdown */}
      <div className="rounded-[28px] border border-white/10 bg-[#07140d] p-5 shadow-[0_22px_70px_rgba(0,0,0,0.35)]">
        <h2 className="mb-3 text-lg font-semibold text-white">Emissions by Category</h2>
        <CategoryBars
          items={(stats?.by_category ?? []).map((c) => ({ label: c.category, value: c.co2_emitted }))}
          unit="kg"
          accent="#f07030"
        />
      </div>

      {/* Recent entries */}
      <div className="rounded-[28px] border border-white/10 bg-[#07140d] p-5 shadow-[0_22px_70px_rgba(0,0,0,0.35)]">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-white">Recent Footprint Entries</h2>
          <Link href="/carbon-footprint/log" className="text-sm font-medium text-[#f07030] hover:underline">
            Log new entry
          </Link>
        </div>
        {recent.length === 0 ? (
          <p className="text-sm text-white/45">No entries logged yet.</p>
        ) : (
          <ul className="space-y-2">
            {recent.map((c) => (
              <li key={c.id} className="flex justify-between rounded border border-white/5 bg-white/5 px-3 py-2">
                <div>
                  <p className="text-sm font-medium capitalize text-white/85">
                    {c.activity} · {c.quantity} {c.unit}
                  </p>
                  <p className="text-[10px] text-white/40">
                    {c.category} · {new Date(c.created_at).toLocaleDateString()}
                  </p>
                </div>
                <span className="text-sm font-semibold text-[#f07030]">+{c.co2_emitted.toFixed(2)} kg</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
